services:
  # Base de données vectorielle Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  # Backend FastAPI (API de recherche)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    volumes:
      - ./backend:/app
    command: python startup.py

  # Backend Admin (API d'administration)
  admin:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    volumes:
      - ./backend:/app
    command: python startup_admin.py

  # Frontend React (pour développement local)
  frontend:
    build: ./frontend/front-chunk
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/front-chunk:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_ADMIN_API_URL=http://localhost:8001
    depends_on:
      - backend
      - admin

volumes:
  qdrant_storage:
